version: "3.9"

services:
  wc-db:
    build:
      context: ./services/wc.database
      dockerfile: src/main/docker/Dockerfile.fast-jar
    ports:
      - "1969:8080"
    volumes:
      - ./services/wc.database/data/:/deployments/data/

  wc-iam:
    build:
      context: ./services/wc.iam
      dockerfile: src/main/docker/Dockerfile.fast-jar
    ports:
      - "8080:8080"
    volumes:
      - ./services/wc.iam/data/:/deployments/data/
    environment: {
      WC_MQ_HOST: "rabbitmq"
    }

  wc-professors:
    build:
      context: ./services/wc.professors
      dockerfile: src/main/docker/Dockerfile.fast-jar
    ports:
      - "8081:8080"
    environment: {
      QUARKUS_HTTP_PORT: 8080,
      WC_DATASOURCE_URL: "http://wc-db:8080"
    }

  wc-students:
    build:
      context: ./services/wc.students
      dockerfile: src/main/docker/Dockerfile.fast-jar
    ports:
      - "8082:8080"
    environment: {
      QUARKUS_HTTP_PORT: 8080,
      WC_DATASOURCE_URL: "http://wc-db:8080"
    }

  wc-faculties:
    build:
      context: ./services/wc.faculties
      dockerfile: src/main/docker/Dockerfile.fast-jar
    ports:
      - "8989:8080"
    environment: {
      WC_DB_URL: "http://wc-db:8080"
    }

  wc-ui:
    build:
      context: ./wc-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
